### Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/quartz_demo?useSSL=false
#    username: quartz
#    password: quartz
#
### Quartz properties
#  quartz:
#    job-store-type: jdbc
#    properties:
#      org:
#        quartz:
#          threadPool:
#            threadCount: 5
