spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:security
#
#    spring:
#      h2:
#        console:
#          enabled: true
#          path: /h2
#      jpa:
#        show-sql: true
#        #Using the right database platform is extremely important on spring boot 2.0
#        database-platform: org.hibernate.dialect.MySQL5Dialect
#        #CONFLICTS with HEROKU from local host
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.MySQL57Dialect
#            ddl-auto: update
#      datasource:
#        url: jdbc:mysql://localhost:3306/jwt?userSSL=false&serverTimezone=UTC
#        username: chisom
#        password: password